### ISSUE TITLE
Some question about configuration files

### ISSUE THREAD

**Issue by linhuixiao** [segwayrobotics/segway_DRIVE_benchmark#2]
Hello, I test your newly upload sample dataset, and also meet some question.

1. In https://drive.segwayrobotics.com/#/dataset/index， the Sample Dataset Config file(*.yaml) your provide is show：
%YAML:1.0
Author: SegwayRobotics
camera_distortion_parameters:
   w: 8.9130900000000002e-01
camera_projection_parameters:
   fx: 2.6186799999999999e+02
   fy: 2.6019200000000001e+02
   cx: 3.2501700000000000e+02
   cy: 2.3733500000000001e+02
I just wonder which camera model should be take in the newly upload sample dataset？ PINHOLE or KANNALA_BRANDT ？If using  PINHOLE model，the distortion_parameters k1, k2, p1, p2 should be given. If using KANNALA_BRANDT model,  the projection_parameters k2~k5,mu,mv,u0,v0 should be given.

2. In https://drive.segwayrobotics.com/#/overview/sensor_setup， your camera  image parameters is：
camera  640x480, global shutter, 30fps
Camera: 133x100x166.5 FOV @10Hz
which image_width and image_height should be taken？which model should be taken? Is fisheye?

**Comment by qinyusen** [comment]
Hi, 

**For the 1st question,** I will give a short explain, from very beginning, since maybe you mix up the camera models.

There are 2 definitions, projection models and  distortion models.

For us we are using **pinhole as projection model**, and **FOV as distortion modle**.
Some  projection model:
1. pinhole camera model  (intrinsics vector: [fu fv pu pv])
2. omnidirectional camera model (intrinsics vector: [xi fu fv pu pv])
3. double sphere camera model (intrinsics vector: [xi alpha fu fv pu pv])
4. extended unified camera model  (intrinsics vector: [alpha beta fu fv pu pv])

Normally we could find these distortion model:
1. radial-tangential   (distortion_coeffs: [k1 k2 r1 r2]) (This maybe what you are talking about PINHOLE modle)
2. equidistant   (distortion_coeffs: [k1 k2 k3 k4])    (This is what you are talking about "**KANNALA_BRANDT model**")
3. FOV   (distortion_coeffs: [w]) (This is what we are using here.)

For the FOV model, you can refer on this paper:
https://hal.inria.fr/inria-00267247/file/distcalib.pdf

And you can find some similar information on : https://github.com/ethz-asl/kalibr/wiki/supported-models

---

 **For the 2nd question:**

"camera 640x480, global shutter, 30fps"
this means the resolution is 640x480 ,which is the image width and height, and running under 30fps

Camera: 133x100x166.5 FOV @10hz
FOV is the field of vision, 133x100x166.5 means the horizontal FOV is 133 degree,  vertical FOV is 100 degree,  and diagonal FOV is 166.5 degree.

Thanks.

**Comment by qinyusen** [comment]
You can try with this modified project :
https://github.com/pangfumin/VINS-Mono

check the readme 3.14

**Comment by qinyusen** [comment]
@linhuixiao  Do you have any further question?
